# Generated by Django 5.2.5 on 2025-09-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-joined_date'], 'verbose_name_plural': 'Student'},
        ),
    ]
